### ISSUE TITLE
error in condbert_inference.ipynb, in the last cell it's not generating the expected output 

### ISSUE THREAD

**Issue by VardhanKumarr** [s-nlp/detox#3]
like it's visible here, this occurred on google colab, didn't change any bit of code, just added imports that's it, can you please resolve this
![Screenshot_20230220_113339](https://user-images.githubusercontent.com/125920901/220189782-759b7c3c-a115-46d1-b478-eae800627cbf.png)

**Comment by VardhanKumarr** [comment]
https://drive.google.com/file/d/1Beb3eC6aA8BhYNOb83FiBiTGfSa7x7Xc/view?usp=sharing

colab notebook for reference

**Comment by avidale** [comment]
Hello Kumar,
thank you for noticing the problem! I was able to reproduce it. 

The cause of the problem was some implementation change in the Transformers library. Originally, we used the `transformers==4.11.1` version. When I specified it in the requirements (before, it was just `transformers` without versioning), the code started working.

You can find here a notebook to reproduce both models: https://colab.research.google.com/drive/1HEUgKO100rSuDcv80prD3dRZSjKztTqk?usp=sharing. 

---------

Anyway, I don't recommend reusing the code from here: both unsupervised models that we propose frequently fail to preserve the semantics of the input. Instead, please consider models trained on the parallel detoxification corpus that we have collected in this paper: https://aclanthology.org/2022.acl-long.469. The code and data for it are available at https://github.com/s-nlp/paradetox.
