### ISSUE TITLE
T5 paraphraser baseline

### ISSUE THREAD

**Issue by BunnyNoBugs** [s-nlp/detox#9]
Hello!

Could you please share some details about the T5 paraphraser baseline? Namely, which model was used -- the original or the one fine-tuned on the subset of ParaNMT? And what parameters for generation were used -- top-k, temperature, number of sequences, etc.?

**Comment by avidale** [comment]
Hi!
We used the one fine-tuned on the subset of ParaNMT. 
The exact code for inference can be found in this notebook: https://github.com/s-nlp/detox/blob/main/emnlp2021/style_transfer/paraGeDi/gedi_inference.ipynb

**Comment by avidale** [comment]
Anyway, for text detoxification we recommend using supervised models, such as https://huggingface.co/s-nlp/bart-base-detox for English or https://huggingface.co/s-nlp/ruT5-base-detox for Russian. They consistently demonstrate better quality that unsupervised models like ParaGeDi.

**Comment by BunnyNoBugs** [comment]
Thank you for your answer! However, if I get it right, the notebook you mention contains inference for ParaGeDi, not the model named "T5 paraphraser (baseline)" in Table 1. If so, could you please share the details about the paraphraser-only baseline, especially the number of sequences?

**Comment by avidale** [comment]
Sorry, initially I didn't understand the question correctly. 

Here is the model that I used for paraphrasing without GeDi: https://huggingface.co/s-nlp/t5-paraphrase-paws-msrp-opinosis-paranmt. In fact, it is exactly the same paraphraser that I used as a part of GeDi. However, I also used a classifier model to choose the least toxic hypothesis from the 10 hypotheses generated by the paraphraser.

Here is the code that I used to generate the "paraphraser only" baseline:
```Python
def paraphrase(text, max_length='auto', beams=10):
    texts = [text] if isinstance(text, str) else text
    texts = [text_processing.text_preprocess(t) for t in texts]
    inputs = tokenizer(texts, return_tensors='pt', padding=True)['input_ids'].to(para.device)
    if max_length == 'auto':
        max_length = min(int(inputs.shape[1] * 1.1) + 4, 64)
    attempts = beams
    out = para.generate(
        inputs, 
        num_beams=beams,
        num_return_sequences=attempts, 
        do_sample=False, 
        temperature=1.0, 
        repetition_penalty=3.0, 
        max_length=max_length,
        bad_words_ids=[[2]],  # unk
        output_scores=True, 
        return_dict_in_generate=True,
    )
    results = [tokenizer.decode(r, skip_special_tokens=True) for r in out.sequences]
    #scores = get_perplexities(out, tokenizer=tokenizer).cpu().numpy()
    scores = np.array([dict(_)['1'] for _ in predictor.predict_batch(results)])
    
    results = [text_processing.text_postprocess(t) for t in results]
    out_texts = []
    for i in range(len(texts)):
        idx = scores[(i*attempts):((i+1)*attempts)].argmin()
        out_texts.append(results[i*attempts+idx])
    return out_texts
```
    
The `text_processing` file is this one: https://github.com/s-nlp/detox/blob/main/emnlp2021/style_transfer/paraGeDi/text_processing.py

The `predictor` is the https://huggingface.co/s-nlp/roberta_toxicity_classifier_v1 classification model (the code for its inference is weird, because it uses the fastbert library, but I recommend you to use the Huggingface python interface instead). It has the same hyperparameters as the https://huggingface.co/s-nlp/roberta_toxicity_classifier that we used for evaluation of all text style transfer method, but was trained on the other half of the Jigsaw toxic commets corpus, to mitigate overfitting to the leaderboard.

As you can see from that leaderbord, though, reranking the paraphraser hypotheses doesn't help much: only 15% of its results are classified as non-toxic.

**Comment by BunnyNoBugs** [comment]
Thank you for the clarification!
